apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumeclaimName }}
  #namespace: client-library
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: ""
  selector:
    matchLabels:
      name: {{ .Values.volumename }}