replicas: 1
version: 'latest'

# Hanium 2021 Kubernetes

## Volume
volumename: hanium-2021-pv
volumeclaimName: hanium-2021-pvc
mountPath: /client-resource
## Client Pod Resource
podname: deployment-pod-resource
podimage: 
# Client Node Resource
nodename: deployment-node-resource
nodeimage: 
# Client NS Resource
nsimage: 
nsname: deployment-ns-resource
# Client SVC Resource
svcimage: 
svcname: deployment-service-resource
# SVC Client 
frontendname: nginx-test
frontendimage: nginx
frontsvc: nginx-test
frontendns: frontend
# SVC Log Report
logreportname: log-report
logsvc: log-report-svc
# SVX Main
firstpage: nginx-main 
firstsvc: main-svc
# Ingress
ingressname: hanium-ingress
ingresspathone: /cluster-info/
ingresspathtwo: /log-report/
ingresspathany: /*
