apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjobsvc }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: {{ .Values.volumename }}
            persistentVolumeClaim:
              claimName: {{ .Values.volumeclaimName }}
          restartPolicy: OnFailure
          containers:
          - name: {{ .Values.svcname }}
            image: {{ .Values.svcimage }}
            resources:
              requests:
                cpu: {{ .Values.cpu }}
                memory: {{ .Values.memory }}
            command: ["sh","-c"]
            args: ["python service.py > /client-resource/service_resource.json"]
            volumeMounts:
            - name: {{ .Values.volumename }}
              mountPath: {{ .Values.mountPath }}
    