kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolenode }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolenode }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.saname }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterrolenode }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolens }}
rules:
- apiGroups: ["*"]
  resources: ["namespaces","pods"]
  verbs: ["get","list","watch"] # get : 개별 리소스 조회 , list : 여러건의 리소스 조회
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolens }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.saname }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterrolens }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolepod }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolepod }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.saname }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterrolepod }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolesvc }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolesvc }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.saname }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterrolesvc }}
  apiGroup: rbac.authorization.k8s.io
