apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount.pod.name }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::238856124133:role/Kubeboard-log-report-cronjob-iam
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount.chart.name }}
