apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-iam-test
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::238856124133:role/Kubeboard-log-report-cronjob-iam
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mychart
