apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-web
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi