kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clientlibrary-helm
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clientlibrary-helm
subjects:
- kind: ServiceAccount
  name: mychart
  namespace: default
roleRef:
  kind: ClusterRole
  name: clientlibrary-helm
  apiGroup: rbac.authorization.k8s.io
