kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clientlibrary-helm-ns
rules:
- apiGroups: ["*"]
  resources: ["namespaces","pods"]
  verbs: ["get","list","watch"] # get : 개별 리소스 조회 , list : 여러건의 리소스 조회
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clientlibrary-helm-ns
subjects:
- kind: ServiceAccount
  name: mychart
  namespace: default
roleRef:
  kind: ClusterRole
  name: clientlibrary-helm-ns
  apiGroup: rbac.authorization.k8s.io
