apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-ns-info
spec:
  schedule: "*/9 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets: 
          - name: regcred
          serviceAccountName: mychart
          containers:
          - name: nodeinfo
            image: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-ns-resource:latest
            command: ["python","ns.py"]

  