kind: Service
apiVersion: v1
metadata:
  name: image-scan-svc
 # namespace: {{ .Values.frontendns }}
spec:
  selector:
    app: image-scan
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3002
  type: LoadBalancer