kind: Service
apiVersion: v1
metadata:
  name: main-frontend-svc
 # namespace: {{ .Values.frontendns }}
spec:
  selector:
    app: main-frontend 
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer
