kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrole.node.name }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrole.node.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.chart.name }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterrole.node.name }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrole.namespace.name }}
rules:
- apiGroups: ["*"]
  resources: ["namespaces","pods"]
  verbs: ["get","list","watch"] # get : 개별 리소스 조회 , list : 여러건의 리소스 조회
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrole.namespace.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.chart.name }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterrole.namespace.name }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrole.pod.name }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrole.pod.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.chart.name }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterrole.pod.name }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrole.service.name }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  {{ .Values.clusterrole.service.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.chart.name }}
  namespace: default
roleRef:
  kind: ClusterRole
  name:  {{ .Values.clusterrole.service.name }}
  apiGroup: rbac.authorization.k8s.io
