{{- define "kubeboard.vulservice" -}}
metadata:
  name: {{ include "kubeboard.fullname" . }}-vul-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
{{- end -}}
{{- include "kubeboard.service" (list . "kubeboard.vulservice" ) }}
