{{- define "common.logreporthpa" -}}
metadata:
  name: {{ include "common.fullname" . }}-log-report-hpa
spec:
  scaleTargetRef:
    name: {{ include "common.fullname" . }}-log-report
{{- end -}}
{{- include "common.hpa" (list . "common.logreporthpa" ) }}
