volume:
  pvname: kubeboard-pv
  pvcname: kubeboard-pvc
  mountpath: /client-resource


cronjob:
  node:
    name: cronjob-node-resource
    image: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-node-resource:latest
  pod:
    name: cronjob-pod-resource
    image: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-pod-resource-all:latest
  service:
    name: cronjob-svc-resource
    image: 38856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-svc-resource:latest
  namespace:
    name: cronjob-ns-resource
    image: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-ns-resource:latest
  logreport:
    name: cronjob-log-report
    image: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/action-log-report:latest
  vulnerability:
    name: cronjob-image-scanner
    image: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/action-log-scanner:latest

serviceaccount:
  pod:
    name: pod-iam
    rolearn: ""
  chart:
    name: kubeboard

# Ingress
ingress:
  name: kubeboard-ingress
  first:
    path: /logging/*
    svcname: svc-log-report
  second:
    path: /vulnerability/*
    svcname: svc-image-scanner
  any:
    path: /*
    svcname: svc-main-fe

clusterrole:
  pod:
    name: rbac-pod
  service:
    name: rbac-svc
  namespace:
    name: rbac-ns
  node:
    name: rbac-node
