apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumename }}
  labels:
    name: {{ .Values.volumename }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1G
  hostPath:
    path: {{ .Values.mountPath }}
    type: DirectoryOrCreate