apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-info
#  namespace: client-library
  labels:
    app: deployment-sevice-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-service-info
  template:
    metadata:
      labels:
        app: deployment-service-info
    spec:
      volumes:
      - name: hanium-2021-pv
        persistentVolumeClaim:
          claimName: hanium-2021-pvc
      containers:
      - name: serviceinfo
        image: sangwondockerhub/service_info
        command: ["sh","-c"]
        args: ["python service.py > /client-resource/service_Info.json"]
        volumeMounts:
        - name: hanium-2021-pv
          mountPath: /client-resource
    