replicas: 1
version: 'latest'

# Hanium 2021 Kubernetes

## Volume
volumename: hanium-2021-pv
volumeclaimName: hanium-2021-pvc
mountPath: /client-resource
## Client Pod Resource
podname: cr-pod-resource
podimage: 
# Client Node Resource
nodename: cr-node-resource
nodeimage: 
# Client NS Resource
nsimage: 
nsname: cr-ns-resource
# Client SVC Resource
svcimage: 
svcname: cr-service-resource
# SVC Client 
frontendname: nginx-test
frontendimage: nginx
frontsvc: nginx-test
frontendns: frontend
# SVC Log Report
logreportname: log-report
logsvc: log-report-svc
# SVC Main
firstpage: nginx-main 
firstsvc: main-svc
# Ingress
ingressname: hanium-ingress
ingresspathone: /cluster-info/
ingresspathtwo: /log-report/
ingresspathany: /*
# resource
cpu: "100m"
memory: "256Mi"
# Cronjob
cronjobns: cronjob-ns-resource
cronjobnode: cronjob-node-resource
cronjobpod: cronjob-pod-resource
cronjobsvc: cronjob-svc-resource
 
