kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clientlibrary-helm-pod
  namespace: client-library
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clientlibrary-helm-pod
subjects:
- kind: ServiceAccount
  name: mychart
  namespace: client-library
roleRef:
  kind: ClusterRole
  name: clientlibrary-helm-pod
  apiGroup: rbac.authorization.k8s.io
