replicas: 1
version: 'latest'

# Hanium 2021 Kubernetes

## Volume
volumename: hanium-2021-pv
volumeclaimName: hanium-2021-pvc
mountPath: /client-resource

## Main Frontned CronJob Resource
podname: cr-pod-resource
podimage: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-pod-resource-all:latest
# Client Node Resource
nodename: cr-node-resource
nodeimage: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-node-resource:latest
# Client NS Resource
nsimage: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-ns-resource:latest
nsname: cr-ns-resource
# Client SVC Resource
svcimage: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-svc-resource:latest
svcname: cr-service-resource
# Log Report CronJob Resource
logreportjob: log-report
logerrorimage: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-cronjob-log-report:latest
# Image Vulnerability CronJob Resource
imagescanjob: image-scanner
imagescannerimage: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-cronjob-image-scanner:latest
# SVC Client 
frontendname: main-frontend
frontendimage: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/action-main-frontend:latest
frontsvc: main-frontend-svc
frontendns: frontend
# SVC Log Report
logreportname: log-report
logsvc: log-report-svc
logreportimage: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/action-log-report:latest
# SVC Main
firstpage: main-frontend 
firstsvc: main-frontend-svc
# Image Vulnerability
imagescanname: image-scanner
imagescansvc: image-scan-svc
imagescanimage: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/action-log-scanner:latest
# Ingress
ingressname: hanium-ingress
ingresspathone: /logging/*
ingresspathtwo: /vulnerability/*
ingresspathany: /*
# resource
cpu: "100m"
memory: "256Mi"
# Cronjob
cronjobns: cronjob-ns-resource
cronjobnode: cronjob-node-resource
cronjobpod: cronjob-pod-resource
cronjobpodlog: cronjob-pod-resource-log
cronjobpodmonitor: cronjob-pod-resource-monitor
cronjobsvc: cronjob-svc-resource
# serviceaccount name
saname: mychart
sapodiam: pod-iam-test
# Clusterrole
clusterrolepod: clientlibrary-helm-pod
clusterrolesvc: clientlibrary-helm-svc
clusterrolens: clientlibrary-helm-ns
clusterrolenode: clientlibrary-helm-node