{{- define "kubeboard.logreportservice" -}}
metadata:
  name: {{ include "kubeboard.fullname" . }}-log-report-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
{{- end -}}
{{- include "kubeboard.service" (list . "kubeboard.logreportservice" ) }}
