apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-pod-iam-test
  labels:
    app: eks-iam-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-iam-test
  template:
    metadata:
      labels:
        app: eks-iam-test
    spec:
      serviceAccountName: pod-iam-test
      containers:
      - name: eks-iam-test
        image: s3-access:latest
 