apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingressname }}
  #namespace: {{ .Values.frontendns }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingresspathone }}
        backend:
          serviceName: {{ .Values.frontsvc }}
          servicePort: 80
      - path: {{ .Values.ingresspathtwo }}
        backend:
          serviceName: {{ .Values.logsvc }}
          servicePort: 80
      - path: {{ .Values.ingresspathany }}
        backend:
          serviceName: {{ .Values.firstsvc }}
          servicePort: 80
          
