apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjobpod }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: {{ .Values.volumename }}
            persistentVolumeClaim:
              claimName: {{ .Values.volumeclaimName }}
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.saname }}
          containers:
          - name: {{ .Values.podname }}
            image: {{ .Values.podimage }}
            command: ["sh","-c"]
            args: ["python pod.py > /client-resource/pod_resource.json"]
            volumeMounts:
            - name: {{ .Values.volumename }}
              mountPath: {{ .Values.mountPath }}
    