kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolenode }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterrolenode }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.saname }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterrolenode }}
  apiGroup: rbac.authorization.k8s.io
