apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nodename }}
  #namespace: client-library
  labels:
    app: {{ .Values.nodename }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nodename }}
  template:
    metadata:
      labels:
        app: {{ .Values.nodename }}
    spec:
      volumes:
      - name: {{ .Values.volumename }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumeclaimName }}
      containers:
      - name: {{ .Values.nodename }}
        image: {{ .Values.nodeimage }}
        command: ["sh","-c"]
        args: ["python Node.py > /client-resource/node_resource.json"]
        volumeMounts:
        - name: {{ .Values.volumename }}
          mountPath: {{ .Values.mountPath }}
    