---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Kubernetes-Enterprise-Log-Analysis-System
  region: ap-northeast-2

availabilityZones: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.medium
