kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clientlibrary-helm-svc
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clientlibrary-helm-svc
subjects:
- kind: ServiceAccount
  name: mychart
  namespace: default
roleRef:
  kind: ClusterRole
  name: clientlibrary-helm-svc
  apiGroup: rbac.authorization.k8s.io
