apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-svc-info
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets: 
          - name: regcred
          serviceAccountName: mychart
          containers:
          - name: svcinfo
            image: 238856124133.dkr.ecr.ap-northeast-1.amazonaws.com/private-svc-resource:latest
            command: ["python","service.py"]

  